[package]
name = "obfw"
version = "0.1.0"
edition = "2021"

[features]
read = []
write = []

[dependencies]
num_enum = { version = "0.7.3", default-features = false }
thiserror = { version = "2.0.3", default-features = false }
